[package]
name = "stap"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = { version = "0.3.30", default-features = false }

[dev-dependencies]
trybuild = "1.0.96"
futures = { version = "0.3.30" }
serde_json = "1.0.117"
